"""batch_size

Revision ID: 8f92ed151af4
Revises: 344a5a043ffd
Create Date: 2025-10-23 19:18:15.697377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f92ed151af4"
down_revision: Union[str, Sequence[str], None] = "344a5a043ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("batch_size", sa.Integer(), nullable=True))
    op.execute("UPDATE nodes SET batch_size = 1 WHERE batch_size IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "batch_size")
    # ### end Alembic commands ###
