"""sub reached

Revision ID: 2fd464988aed
Revises: 6555ae2ca544
Create Date: 2025-10-22 15:15:27.525486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fd464988aed"
down_revision: Union[str, Sequence[str], None] = "6555ae2ca544"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("setting")
    op.add_column("subscriptions", sa.Column("reached", sa.Boolean(), nullable=True))
    op.execute("UPDATE subscriptions SET reached = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "reached")
    op.create_table(
        "setting",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("setting_pkey")),
    )
    # ### end Alembic commands ###
