"""admin current usages

Revision ID: 1720e96455fa
Revises: ce502e076000
Create Date: 2025-11-25 01:41:16.129037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1720e96455fa"
down_revision: Union[str, Sequence[str], None] = "ce502e076000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("current_usage", sa.BigInteger(), nullable=True))
    op.execute("""
        UPDATE admins
        SET current_usage = (
            SELECT COALESCE(SUM(
                (
                    SELECT COALESCE(SUM(su.usage), 0)
                    FROM subscription_usages su
                    WHERE su.subscription_id = s.id
                )
            ), 0)
            FROM subscriptions s
            WHERE s.owner_id = admins.id
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "current_usage")
    # ### end Alembic commands ###
