"""admin access prefix

Revision ID: ea629f8690e6
Revises: b00bd4e3c945
Create Date: 2025-10-19 16:49:40.008011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea629f8690e6"
down_revision: Union[str, Sequence[str], None] = "b00bd4e3c945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("access_prefix", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "access_prefix")
    # ### end Alembic commands ###
