"""ability to set null node

Revision ID: ed78f04e17bd
Revises: 89325dcf385b
Create Date: 2025-10-05 18:39:41.255242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed78f04e17bd"
down_revision: Union[str, Sequence[str], None] = "89325dcf385b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nodes", "remark", existing_type=sa.VARCHAR(length=128), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nodes", "remark", existing_type=sa.VARCHAR(length=128), nullable=False)
    # ### end Alembic commands ###
