"""onreached

Revision ID: 1d24581b85eb
Revises: e12660ca9607
Create Date: 2025-11-03 15:32:12.020325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d24581b85eb"
down_revision: Union[str, Sequence[str], None] = "e12660ca9607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("onreached_expire", sa.Boolean(), nullable=True))
    op.add_column("subscriptions", sa.Column("onreached_usage", sa.Boolean(), nullable=True))
    op.execute("UPDATE subscriptions SET onreached_expire = FALSE, onreached_usage = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "onreached_usage")
    op.drop_column("subscriptions", "onreached_expire")
    # ### end Alembic commands ###
