"""sub usage _usage

Revision ID: ce502e076000
Revises: 965b9073fd1f
Create Date: 2025-11-17 17:17:53.115386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce502e076000"
down_revision: Union[str, Sequence[str], None] = "965b9073fd1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription_usages", sa.Column("_usage", sa.BigInteger(), nullable=True))
    op.execute("UPDATE subscription_usages SET _usage = usage WHERE _usage IS NULL")
    op.alter_column("subscription_usages", "_usage", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_usages", "_usage")
    # ### end Alembic commands ###
