"""admin guards

Revision ID: 24e4a7906b72
Revises: d06cccf84aa9
Create Date: 2025-11-29 20:06:19.640665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24e4a7906b72"
down_revision: Union[str, Sequence[str], None] = "d06cccf84aa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("support_url", sa.String(length=256), nullable=True))
    op.add_column("admins", sa.Column("update_interval", sa.Integer(), nullable=True))
    op.execute("UPDATE admins SET update_interval = 1 WHERE update_interval IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "update_interval")
    op.drop_column("admins", "support_url")
    # ### end Alembic commands ###
