"""admin announce

Revision ID: 2eba727f259c
Revises: 24e4a7906b72
Create Date: 2025-12-01 04:49:51.676213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2eba727f259c"
down_revision: Union[str, Sequence[str], None] = "24e4a7906b72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("announce", sa.String(length=256), nullable=True))
    op.add_column("admins", sa.Column("announce_url", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "announce_url")
    op.drop_column("admins", "announce")
    # ### end Alembic commands ###
