"""del service times

Revision ID: 25a7cfe0804f
Revises: db3cfa47674e
Create Date: 2025-10-05 15:47:10.834092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25a7cfe0804f"
down_revision: Union[str, Sequence[str], None] = "db3cfa47674e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "created_at")
    op.drop_column("services", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "services",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
