"""last backup

Revision ID: 4a4fa5ea737e
Revises: 20251203_auto_renewal
Create Date: 2025-12-08 20:15:31.595548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a4fa5ea737e"
down_revision: Union[str, Sequence[str], None] = "20251203_auto_renewal"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("last_backup_at", sa.DateTime(), nullable=True))
    op.drop_column("subscription_auto_renewals", "created_at")
    op.drop_column("subscription_auto_renewals", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_auto_renewals",
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "subscription_auto_renewals",
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    )
    op.drop_column("admins", "last_backup_at")
    # ### end Alembic commands ###
