"""admins api key

Revision ID: e59d2124515b
Revises: 8f92ed151af4
Create Date: 2025-10-23 21:33:49.660812

"""

from secrets import token_hex
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e59d2124515b"
down_revision: Union[str, Sequence[str], None] = "8f92ed151af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("api_key", sa.String(length=64), nullable=True))
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE admins SET api_key = :api_key"), {"api_key": token_hex(32)})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "api_key")
    # ### end Alembic commands ###
