"""more time in admins

Revision ID: e11073c3d16e
Revises: b015c80edd58
Create Date: 2025-10-19 00:56:40.870089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e11073c3d16e"
down_revision: Union[str, Sequence[str], None] = "b015c80edd58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("removed_at", sa.DateTime(), nullable=True))
    op.add_column("admins", sa.Column("last_online_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "last_online_at")
    op.drop_column("admins", "removed_at")
    # ### end Alembic commands ###
