"""null username

Revision ID: c24f551241ec
Revises: 67a071d78f71
Create Date: 2025-10-30 13:13:45.745814

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c24f551241ec"
down_revision: Union[str, Sequence[str], None] = "67a071d78f71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ## set null username for removed true
    op.execute("UPDATE subscriptions SET username = NULL WHERE removed = TRUE;")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
