"""migration keys

Revision ID: e12660ca9607
Revises: 4bccc7fa2357
Create Date: 2025-11-01 13:30:09.588859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e12660ca9607"
down_revision: Union[str, Sequence[str], None] = "4bccc7fa2357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_migrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("migration_key", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_migrations_id"), "subscription_migrations", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscription_migrations_subscription_id"), "subscription_migrations", ["subscription_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_migrations_subscription_id"), table_name="subscription_migrations")
    op.drop_index(op.f("ix_subscription_migrations_id"), table_name="subscription_migrations")
    op.drop_table("subscription_migrations")
    # ### end Alembic commands ###
