"""add inactive at to subs

Revision ID: 50dcca6cf4fd
Revises: 044435c2626d
Create Date: 2025-10-06 02:13:33.657530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50dcca6cf4fd"
down_revision: Union[str, Sequence[str], None] = "044435c2626d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("inactive_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "inactive_at")
    # ### end Alembic commands ###
