"""del node remark uniqe

Revision ID: 8389b8e43ad0
Revises: 50dcca6cf4fd
Create Date: 2025-10-18 21:56:30.703804

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8389b8e43ad0"
down_revision: Union[str, Sequence[str], None] = "50dcca6cf4fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nodes_remark"), table_name="nodes")
    op.create_index(op.f("ix_nodes_remark"), "nodes", ["remark"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nodes_remark"), table_name="nodes")
    op.create_index(op.f("ix_nodes_remark"), "nodes", ["remark"], unique=True)
    # ### end Alembic commands ###
