"""service remove

Revision ID: 344a5a043ffd
Revises: 2fd464988aed
Create Date: 2025-10-23 18:19:51.998252

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "344a5a043ffd"
down_revision: Union[str, Sequence[str], None] = "2fd464988aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("service_admin_association_service_id_fkey"), "service_admin_association", type_="foreignkey")
    op.create_foreign_key(None, "service_admin_association", "services", ["service_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("service_node_association_service_id_fkey"), "service_node_association", type_="foreignkey")
    op.create_foreign_key(None, "service_node_association", "services", ["service_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_node_association", type_="foreignkey")
    op.create_foreign_key(
        op.f("service_node_association_service_id_fkey"), "service_node_association", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "service_admin_association", type_="foreignkey")
    op.create_foreign_key(
        op.f("service_admin_association_service_id_fkey"), "service_admin_association", "services", ["service_id"], ["id"]
    )
    # ### end Alembic commands ###
