"""seller

Revision ID: b97e019b144a
Revises: 4763f1a290c9
Create Date: 2025-11-04 04:35:58.043228

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b97e019b144a"
down_revision: Union[str, Sequence[str], None] = "4763f1a290c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE admins SET role='seller' WHERE role='reseller'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
