"""node priority

Revision ID: 3c8f4a2b1e9d
Revises: 2eba727f259c
Create Date: 2025-12-01 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c8f4a2b1e9d"
down_revision: Union[str, Sequence[str], None] = "2eba727f259c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("priority", sa.Integer(), nullable=True))
    op.execute("UPDATE nodes SET priority = 0 WHERE priority IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "priority")
    # ### end Alembic commands ###
