"""subs search index

Revision ID: 7c417141283a
Revises: c1d2e3f4g5h6
Create Date: 2025-12-30 02:45:07.080779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c417141283a"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4g5h6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_subscriptions_created_at"), "subscriptions", ["created_at"], unique=False)
    op.create_index(op.f("ix_subscriptions_owner_id"), "subscriptions", ["owner_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_removed"), "subscriptions", ["removed"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_removed"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_owner_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_created_at"), table_name="subscriptions")
    # ### end Alembic commands ###
