"""discord

Revision ID: f81e20dbaa0e
Revises: 4a4fa5ea737e
Create Date: 2025-12-08 20:49:42.384641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f81e20dbaa0e"
down_revision: Union[str, Sequence[str], None] = "4a4fa5ea737e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("discord_webhook_status", sa.Boolean(), nullable=True))
    op.add_column("admins", sa.Column("discord_webhook_url", sa.String(length=256), nullable=True))
    op.add_column("subscriptions", sa.Column("discord_webhook_url", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "discord_webhook_url")
    op.drop_column("admins", "discord_webhook_url")
    op.drop_column("admins", "discord_webhook_status")
    # ### end Alembic commands ###
