"""add subcriptions

Revision ID: 89325dcf385b
Revises: 25a7cfe0804f
Create Date: 2025-10-05 18:30:28.771903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89325dcf385b"
down_revision: Union[str, Sequence[str], None] = "25a7cfe0804f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("access_key", sa.String(length=32), nullable=True),
        sa.Column("server_key", sa.String(length=32), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("activated", sa.Boolean(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=True),
        sa.Column("limit_usage", sa.BigInteger(), nullable=True),
        sa.Column("reset_usage", sa.BigInteger(), nullable=True),
        sa.Column("limit_expire", sa.BigInteger(), nullable=True),
        sa.Column("last_reset_at", sa.DateTime(), nullable=True),
        sa.Column("last_revoke_at", sa.DateTime(), nullable=True),
        sa.Column("last_request_at", sa.DateTime(), nullable=True),
        sa.Column("last_client_agent", sa.String(length=256), nullable=True),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["admins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_table(
        "subscription_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("usage", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_usages_id"), "subscription_usages", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscription_usages_node_id"),
        "subscription_usages",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_usages_subscription_id"),
        "subscription_usages",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_usages_subscription_id"), table_name="subscription_usages")
    op.drop_index(op.f("ix_subscription_usages_node_id"), table_name="subscription_usages")
    op.drop_index(op.f("ix_subscription_usages_id"), table_name="subscription_usages")
    op.drop_table("subscription_usages")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
