"""node offset link

Revision ID: 6555ae2ca544
Revises: ea629f8690e6
Create Date: 2025-10-20 16:23:11.471053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6555ae2ca544"
down_revision: Union[str, Sequence[str], None] = "ea629f8690e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("offset_link", sa.Integer(), nullable=True))
    op.execute("UPDATE nodes SET offset_link = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "offset_link")
    # ### end Alembic commands ###
