"""fix node access

Revision ID: 253b0a3c0adf
Revises: 399a0ba075ca
Create Date: 2025-10-04 02:30:55.589423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "253b0a3c0adf"
down_revision: Union[str, Sequence[str], None] = "399a0ba075ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodes_access")
    op.add_column("nodes", sa.Column("access", sa.String(length=256), nullable=True))
    op.add_column("nodes", sa.Column("access_updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "access_updated_at")
    op.drop_column("nodes", "access")
    op.create_table(
        "nodes_access",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("access", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("node_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], name=op.f("nodes_access_node_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("nodes_access_pkey")),
    )
    # ### end Alembic commands ###
