"""admin max links

Revision ID: ffdbda7a9113
Revises: 11ecc70c9c6a
Create Date: 2025-10-19 16:43:29.078297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffdbda7a9113"
down_revision: Union[str, Sequence[str], None] = "11ecc70c9c6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("max_links", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "max_links")
    # ### end Alembic commands ###
