"""node usage rate

Revision ID: 965b9073fd1f
Revises: 2ac6394e7280
Create Date: 2025-11-17 17:04:02.675834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "965b9073fd1f"
down_revision: Union[str, Sequence[str], None] = "2ac6394e7280"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("usage_rate", sa.Float(), nullable=True))
    op.execute("UPDATE nodes SET usage_rate = 1.0 WHERE usage_rate IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "usage_rate")
    # ### end Alembic commands ###
