"""admin notifs

Revision ID: 3c2f5a589e5f
Revises: 1720e96455fa
Create Date: 2025-11-28 14:54:57.970395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c2f5a589e5f"
down_revision: Union[str, Sequence[str], None] = "1720e96455fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("telegram_id", sa.String(length=256), nullable=True))
    op.add_column("admins", sa.Column("telegram_token", sa.String(length=256), nullable=True))
    op.add_column("admins", sa.Column("expire_warning_days", sa.Integer(), nullable=True))
    op.add_column("admins", sa.Column("usage_warning_percent", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "usage_warning_percent")
    op.drop_column("admins", "expire_warning_days")
    op.drop_column("admins", "telegram_token")
    op.drop_column("admins", "telegram_id")
    # ### end Alembic commands ###
