"""admin placeholder

Revision ID: 11ecc70c9c6a
Revises: cd75670cbf75
Create Date: 2025-10-19 16:20:44.555297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11ecc70c9c6a"
down_revision: Union[str, Sequence[str], None] = "cd75670cbf75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("placeholders", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "placeholders")
    # ### end Alembic commands ###
