"""del mig

Revision ID: 4763f1a290c9
Revises: 1d24581b85eb
Create Date: 2025-11-04 04:10:19.885428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4763f1a290c9"
down_revision: Union[str, Sequence[str], None] = "1d24581b85eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_migrations_id"), table_name="subscription_migrations")
    op.drop_index(op.f("ix_subscription_migrations_subscription_id"), table_name="subscription_migrations")
    op.drop_table("subscription_migrations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_migrations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("migration_key", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], name=op.f("subscription_migrations_subscription_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subscription_migrations_pkey")),
    )
    op.create_index(
        op.f("ix_subscription_migrations_subscription_id"), "subscription_migrations", ["subscription_id"], unique=False
    )
    op.create_index(op.f("ix_subscription_migrations_id"), "subscription_migrations", ["id"], unique=False)
    # ### end Alembic commands ###
