"""add subscription logs

Revision ID: 044435c2626d
Revises: ed78f04e17bd
Create Date: 2025-10-05 23:30:51.163607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "044435c2626d"
down_revision: Union[str, Sequence[str], None] = "ed78f04e17bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("usage", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_logs_id"), "subscription_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscription_logs_subscription_id"),
        "subscription_logs",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_logs_subscription_id"), table_name="subscription_logs")
    op.drop_index(op.f("ix_subscription_logs_id"), table_name="subscription_logs")
    op.drop_table("subscription_logs")
    # ### end Alembic commands ###
