"""add reached at

Revision ID: df3b4d6a533c
Revises: e59d2124515b
Create Date: 2025-10-24 15:45:53.768209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df3b4d6a533c"
down_revision: Union[str, Sequence[str], None] = "e59d2124515b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("reached_at", sa.DateTime(), nullable=True))
    op.execute(
        """
        UPDATE subscriptions
        SET reached_at = created_at
        WHERE reached = TRUE AND reached_at IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "reached_at")
    # ### end Alembic commands ###
