"""add admins

Revision ID: db3cfa47674e
Revises: 253b0a3c0adf
Create Date: 2025-10-05 01:23:30.673696

"""

import hashlib
from secrets import token_hex
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db3cfa47674e"
down_revision: Union[str, Sequence[str], None] = "253b0a3c0adf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.Column("secret", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("last_password_reset_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    secret = token_hex(16)
    op.execute(
        sa.text(
            "INSERT INTO admins (id, enabled, removed, username, password, secret, role, last_password_reset_at, last_login_at, created_at, updated_at) "
            "VALUES (:id, :enabled, :removed, :username, :password, :secret, :role, :last_password_reset_at, :last_login_at, :created_at, :updated_at)"
        ).bindparams(
            id=1,
            enabled=True,
            removed=False,
            username="owner",
            password=hashlib.sha256("owner".encode()).hexdigest(),
            secret=secret,
            role="owner",
            last_password_reset_at=None,
            last_login_at=None,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )
    )

    op.create_table(
        "service_admin_association",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("service_id", "admin_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_admin_association")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
