"""discord send subs

Revision ID: 12f2dfdbcce5
Revises: f81e20dbaa0e
Create Date: 2025-12-08 21:05:34.734276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12f2dfdbcce5"
down_revision: Union[str, Sequence[str], None] = "f81e20dbaa0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("discord_send_subscriptions", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "discord_send_subscriptions")
    # ### end Alembic commands ###
