"""username tag

Revision ID: d06cccf84aa9
Revises: 4d3e6b790f6a
Create Date: 2025-11-29 19:45:03.285256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d06cccf84aa9"
down_revision: Union[str, Sequence[str], None] = "4d3e6b790f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("username_tag", sa.Boolean(), nullable=True))
    op.execute("UPDATE admins SET username_tag = false WHERE username_tag IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "username_tag")
    # ### end Alembic commands ###
