"""add nodes

Revision ID: 1dde254af02e
Revises: 04ad091350db
Create Date: 2025-10-04 01:32:59.735929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dde254af02e"
down_revision: Union[str, Sequence[str], None] = "04ad091350db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=True),
        sa.Column("remark", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.Column("host", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_id"), "nodes", ["id"], unique=False)
    op.create_index(op.f("ix_nodes_remark"), "nodes", ["remark"], unique=True)
    op.create_table(
        "nodes_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access", sa.String(length=512), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodes_access")
    op.drop_index(op.f("ix_nodes_remark"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_id"), table_name="nodes")
    op.drop_table("nodes")
    # ### end Alembic commands ###
