"""debted

Revision ID: 28dd2772f721
Revises: ba4d1805c227
Create Date: 2025-12-21 23:34:43.153224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28dd2772f721"
down_revision: Union[str, Sequence[str], None] = "ba4d1805c227"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("debted", sa.Boolean(), nullable=True))
    op.execute("UPDATE subscriptions SET debted = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "debted")
    # ### end Alembic commands ###
