"""admin access

Revision ID: cd75670cbf75
Revises: e11073c3d16e
Create Date: 2025-10-19 01:07:39.292041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd75670cbf75"
down_revision: Union[str, Sequence[str], None] = "e11073c3d16e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("create_access", sa.Boolean(), nullable=True))
    op.add_column("admins", sa.Column("update_access", sa.Boolean(), nullable=True))
    op.add_column("admins", sa.Column("remove_access", sa.Boolean(), nullable=True))
    op.add_column("admins", sa.Column("count_limit", sa.Integer(), nullable=True))
    op.add_column("admins", sa.Column("usage_limit", sa.Integer(), nullable=True))
    op.execute("UPDATE admins SET create_access = True, update_access = True, remove_access = True")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "usage_limit")
    op.drop_column("admins", "count_limit")
    op.drop_column("admins", "remove_access")
    op.drop_column("admins", "update_access")
    op.drop_column("admins", "create_access")
    # ### end Alembic commands ###
