"""fix usage limit

Revision ID: 4bccc7fa2357
Revises: c24f551241ec
Create Date: 2025-10-30 19:24:05.096387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bccc7fa2357"
down_revision: Union[str, Sequence[str], None] = "c24f551241ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "usage_limit", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "usage_limit", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
