"""totp

Revision ID: a96459a95008
Revises: 12f2dfdbcce5
Create Date: 2025-12-08 23:16:43.527021

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a96459a95008"
down_revision: Union[str, Sequence[str], None] = "12f2dfdbcce5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("totp_secret", sa.String(length=32), nullable=True))
    op.add_column("admins", sa.Column("totp_status", sa.Boolean(), nullable=True))
    op.add_column("admins", sa.Column("last_totp_revoked_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "last_totp_revoked_at")
    op.drop_column("admins", "totp_status")
    op.drop_column("admins", "totp_secret")
    # ### end Alembic commands ###
