"""access title and desc

Revision ID: 67a071d78f71
Revises: df3b4d6a533c
Create Date: 2025-10-30 01:06:04.711111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67a071d78f71"
down_revision: Union[str, Sequence[str], None] = "df3b4d6a533c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("access_title", sa.String(length=64), nullable=True))
    op.add_column("admins", sa.Column("access_description", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "access_description")
    op.drop_column("admins", "access_title")
    # ### end Alembic commands ###
