"""totp pending

Revision ID: 678e52d83caf
Revises: a96459a95008
Create Date: 2025-12-09 00:13:10.379722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "678e52d83caf"
down_revision: Union[str, Sequence[str], None] = "a96459a95008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("totp_secret_pending", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "totp_secret_pending")
    # ### end Alembic commands ###
