"""created at index usage logs

Revision ID: ba4d1805c227
Revises: 678e52d83caf
Create Date: 2025-12-19 21:48:01.525499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba4d1805c227"
down_revision: Union[str, Sequence[str], None] = "678e52d83caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_subscription_logs_created_at"), "subscription_logs", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_logs_created_at"), table_name="subscription_logs")
    # ### end Alembic commands ###
