"""access tag

Revision ID: 63ad0e5bcd75
Revises: 28dd2772f721
Create Date: 2025-12-26 01:44:58.979832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63ad0e5bcd75"
down_revision: Union[str, Sequence[str], None] = "28dd2772f721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("access_tag", sa.String(length=30), nullable=True))
    op.execute("UPDATE admins SET access_tag = 'guards' WHERE access_tag IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "access_tag")
    # ### end Alembic commands ###
