"""del service remark uniqe

Revision ID: b015c80edd58
Revises: 8389b8e43ad0
Create Date: 2025-10-18 22:06:43.191609

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b015c80edd58"
down_revision: Union[str, Sequence[str], None] = "8389b8e43ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_remark"), table_name="services")
    op.create_index(op.f("ix_services_remark"), "services", ["remark"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_remark"), table_name="services")
    op.create_index(op.f("ix_services_remark"), "services", ["remark"], unique=True)
    # ### end Alembic commands ###
