"""admin suffle links

Revision ID: b00bd4e3c945
Revises: ffdbda7a9113
Create Date: 2025-10-19 16:46:33.955608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b00bd4e3c945"
down_revision: Union[str, Sequence[str], None] = "ffdbda7a9113"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("shuffle_links", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "shuffle_links")
    # ### end Alembic commands ###
