"""rate display

Revision ID: f30bfb8700ae
Revises: 90c0df907b35
Create Date: 2026-02-08 14:58:48.917651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f30bfb8700ae"
down_revision: Union[str, Sequence[str], None] = "90c0df907b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("rate_display", sa.String(length=32), nullable=True))
    op.execute("UPDATE nodes SET rate_display = '1.0' WHERE rate_display IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "rate_display")
    # ### end Alembic commands ###
