"""config rename

Revision ID: 90c0df907b35
Revises: f2a7ad0d6539
Create Date: 2026-02-08 11:26:21.355975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90c0df907b35"
down_revision: Union[str, Sequence[str], None] = "f2a7ad0d6539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("config_rename", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "config_rename")
    # ### end Alembic commands ###
