"""node show configs

Revision ID: f2a7ad0d6539
Revises: 123456abcdef
Create Date: 2026-02-07 20:58:02.994300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2a7ad0d6539"
down_revision: Union[str, Sequence[str], None] = "123456abcdef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("show_configs", sa.Boolean(), nullable=True))
    op.execute("UPDATE nodes SET show_configs = true WHERE show_configs IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "show_configs")
    # ### end Alembic commands ###
