"""del node rate

Revision ID: af57c9b0b46b
Revises: 2c273eaf377c
Create Date: 2026-02-24 17:19:30.315691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af57c9b0b46b'
down_revision: Union[str, Sequence[str], None] = '2c273eaf377c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'rate_display')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('rate_display', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
