"""subs changed

Revision ID: 458257a652dd
Revises: 65bf4902a9ce
Create Date: 2026-01-28 00:03:34.931606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "458257a652dd"
down_revision: Union[str, Sequence[str], None] = "65bf4902a9ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("changed", sa.Boolean(), nullable=True))
    op.execute("UPDATE subscriptions SET changed = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "changed")
    # ### end Alembic commands ###
