"""subs index access key

Revision ID: 65bf4902a9ce
Revises: 7c417141283a
Create Date: 2026-01-04 18:04:42.355620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65bf4902a9ce"
down_revision: Union[str, Sequence[str], None] = "7c417141283a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_subscriptions_access_key"), "subscriptions", ["access_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_access_key"), table_name="subscriptions")
    # ### end Alembic commands ###
