"""node scripts

Revision ID: ba54ac57f9ce
Revises: 458257a652dd
Create Date: 2026-01-29 02:56:00.696045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba54ac57f9ce"
down_revision: Union[str, Sequence[str], None] = "458257a652dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("script_secret", sa.String(length=256), nullable=True))
    op.add_column("nodes", sa.Column("script_url", sa.String(length=512), nullable=True))
    op.execute("UPDATE nodes SET script_url = '', script_secret = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "script_url")
    op.drop_column("nodes", "script_secret")
    # ### end Alembic commands ###
